import test from 'node:test';
import assert from 'node:assert/strict';
import { randomBytes } from 'node:crypto';
import { mkdtemp, rm } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import request from 'supertest';
import * as OTPAuth from 'otpauth';
import { loadEnvironment, validateEnv } from '../../config/env.js';
import { createDatabase } from '../../config/database.js';
import { createJwt } from '../../config/jwt.js';
import { createApp } from '../../app.js';
import { createIdentityModel } from '../../models/identityModel.js';
import { createIdentityService } from '../../services/identityService.js';
import { createProfileService } from '../../services/profileService.js';
import { createLogQueue } from '../../services/logService.js';
import { migrationPlan } from '../../scripts/migrationPlan.js';
import { applyPlan } from '../../scripts/migrate.js';
import { bootstrapAdmin } from '../../scripts/bootstrapAdmin.js';
import { hashPassword } from '../../utils/identityCrypto.js';
import { testEnvironment } from '../helpers.js';
import { unavailableIdentityProviders } from '../../providers/identityProviders.js';
import { createImageStorage } from '../../models/imageStorage.js';

loadEnvironment();
const enabled = process.env.RUN_IDENTITY_MYSQL_TESTS === 'true';
test('MySQL identidade real: baseline vazio + upgrade, HTTP, constraints e concorrência', { skip: !enabled && 'RUN_IDENTITY_MYSQL_TESTS/TEST_DB_* ausentes; exige schema _test vazio, isolado e confirmado' }, async t => {
    const env = process.env;
    assert.notEqual(env.NODE_ENV, 'production');
    assert.equal(env.TEST_DB_CONFIRMED_NON_PRODUCTION, 'true');
    assert.match(env.TEST_DB_NAME ?? '', /^[a-zA-Z0-9_]+_test$/);
    assert.notEqual(env.TEST_DB_NAME, env.DB_NAME);
    for (const k of ['TEST_DB_HOST', 'TEST_DB_USER', 'TEST_DB_PASSWORD']) assert.ok(env[k], `${k} obrigatório`);
    const settings = { host: env.TEST_DB_HOST, port: Number(env.TEST_DB_PORT ?? 3306), user: env.TEST_DB_USER, password: env.TEST_DB_PASSWORD, database: env.TEST_DB_NAME, timeout: 30000, connectionLimit: 5, queueLimit: 20 };
    const database = createDatabase(settings);
    t.after(() => database.close());
    const [[count]] = await database.execute('SELECT COUNT(*) AS total FROM information_schema.TABLES WHERE TABLE_SCHEMA = DATABASE()');
    assert.equal(Number(count.total), 0, 'Schema deve estar vazio. Suíte não apaga nem reutiliza dados existentes.');
    const plan = await migrationPlan();
    await applyPlan(database, plan.filter(p => !p.name.startsWith('20261008')));
    const password = 'Isolated!Fixture123';
    await database.execute('INSERT INTO usuarios (nome,email,cpf,senha,tipo_usuario,status,data_nascimento) VALUES (?,?,?,?,?,?,?)', ['Legacy Fixture', ' Legacy@Example.invalid ', '529.982.247-25', await hashPassword(password, 10), 'CLIENTE', 'ATIVO', '2000-01-01']);
    await applyPlan(database, plan);
    await applyPlan(database, plan); // Reexecução lê ledger; não repete DDL.
    const model = createIdentityModel(database);
    const legacy = await model.byEmail('legacy@example.invalid');
    assert.ok(legacy); assert.equal(legacy.cpf, '529.982.247-25');
    const imageRoot = await mkdtemp(join(tmpdir(), 'cineastra-sql-gallery-'));
    t.after(() => rm(imageRoot, { recursive: true, force: true }));
    const config = validateEnv(testEnvironment({ BCRYPT_COST: '10', TWO_FACTOR_ENCRYPTION_KEY: randomBytes(32).toString('base64'), TERMS_VERSION: 'fixture-v1', PRIVACY_VERSION: 'fixture-v1', IDENTITY_LEGAL_BASIS: 'Fixture isolada', RATE_LIMIT_MAX: '1000', IMAGE_STAGING_DIR: join(imageRoot, 'staging'), IMAGE_GALLERY_DIR: join(imageRoot, 'gallery') }));
    const sent = [];
    const providers = { ...unavailableIdentityProviders(), email: { async assertAvailable() {}, async sendRecovery(data) { sent.push(data); } } };
    const tokens = createJwt(config.jwt);
    const identity = createIdentityService({ database, model, config, tokens, providers });
    const profile = createProfileService({ identity, config, providers });
    const logQueue = createLogQueue(async () => {}, { limit: 100 });
    const app = createApp({ config, database, logQueue, retention: { async check() { return true; } }, identityProviders: providers, captchaProvider: { async verify() { return true; } } });
    t.after(async () => { await app.locals.close(); await logQueue.close(); });
    // IDs acima de 2^53 em tabela exclusiva desta base de teste.
    await database.execute('ALTER TABLE sessoes_autenticacao AUTO_INCREMENT = 9007199254740993');
    let auth = await identity.login({ email: 'legacy@example.invalid', password });
    assert.equal(tokens.verify(auth.accessToken).sid, '9007199254740993');
    const ctx = () => { const c = tokens.verify(auth.accessToken); return { actor: { id: c.sub, sessionId: c.sid } }; };
    await t.test('HTTP usa sessão SQL real; logout revoga JWT', async () => {
        await request(app).get('/api/users/me').set('Authorization', `Bearer ${auth.accessToken}`).expect(200);
        await request(app).post('/api/auth/logout').set('Authorization', `Bearer ${auth.accessToken}`).expect(204);
        await request(app).get('/api/users/me').set('Authorization', `Bearer ${auth.accessToken}`).expect(401);
        auth = await identity.login({ email: 'legacy@example.invalid', password });
    });
    await t.test('duas escritas de endereço principal deixam exatamente um principal', async () => {
        const input = { logradouro: 'Fixture', numero: '1', cidade: 'Fixture', estado: 'SP', principal: true };
        await Promise.all([profile.mutate('addresses', null, input, false, ctx()), profile.mutate('addresses', null, input, false, ctx())]);
        const [[row]] = await database.execute('SELECT COUNT(*) AS total FROM enderecos WHERE id_usuario = ? AND principal = TRUE', [String(legacy.id_usuario)]);
        assert.equal(Number(row.total), 1);
        await assert.rejects(database.execute('INSERT INTO enderecos (id_usuario,principal) VALUES (?,TRUE)', [String(legacy.id_usuario)]), { code: 'ER_DUP_ENTRY' });
    });
    await t.test('unicidade de CPF normalizado e rollback de auditoria junto à operação', async () => {
        await assert.rejects(database.execute('INSERT INTO usuarios (nome,email,cpf,senha,tipo_usuario,status) VALUES (?,?,?,?,?,?)', ['Duplicate Fixture', 'duplicate@example.invalid', '52998224725', legacy.senha, 'CLIENTE', 'ATIVO']), { code: 'ER_DUP_ENTRY' });
        await assert.rejects(database.transaction(async c => { await model.updateUser(c, String(legacy.id_usuario), { nome: 'Must rollback' }); await identity.audit(c, 'IDENTITY.TEST_ROLLBACK', String(legacy.id_usuario)); throw new Error('rollback'); }));
        assert.equal((await model.user(String(legacy.id_usuario))).nome, 'Legacy Fixture');
        const [[r]] = await database.execute("SELECT COUNT(*) AS total FROM auditoria_eventos WHERE event_type = 'IDENTITY.TEST_ROLLBACK'"); assert.equal(Number(r.total), 0);
    });
    await t.test('reset concorrente consome uma vez e revoga sessão persistida', async () => {
        // Fixture legado normalizado para entrega; teste não utiliza e-mail externo.
        await database.execute('UPDATE usuarios SET email = ? WHERE id_usuario = ?', ['legacy@example.invalid', String(legacy.id_usuario)]);
        await identity.forgot({ email: 'legacy@example.invalid' });
        const input = { token: sent.at(-1).token, password: 'Changed!Fixture123', passwordConfirmation: 'Changed!Fixture123' };
        const results = await Promise.allSettled([identity.reset(input), identity.reset(input)]);
        assert.equal(results.filter(r => r.status === 'fulfilled').length, 1);
        await request(app).get('/api/users/me').set('Authorization', `Bearer ${auth.accessToken}`).expect(401);
    });
    await t.test('bootstrap único, enrollment e duplo verify SQL não emitem duas sessões', async () => {
        const input = { name: 'Admin Fixture', email: 'admin@example.invalid', cpf: '11144477735', dateOfBirth: '2000-01-01', password, passwordConfirmation: password };
        await bootstrapAdmin(database, config, input);
        await assert.rejects(bootstrapAdmin(database, config, input));
        const login = await identity.login({ email: input.email, password });
        assert.equal(login.accessToken, undefined);
        const enroll = await identity.enroll({ method: 'APP', challengeToken: login.challengeToken });
        const code = OTPAuth.URI.parse(enroll.provisioningUri).generate();
        const results = await Promise.allSettled([identity.verify({ challengeToken: enroll.challengeToken, code }), identity.verify({ challengeToken: enroll.challengeToken, code })]);
        assert.equal(results.filter(r => r.status === 'fulfilled').length, 1);
        const adminToken = results.find(r => r.status === 'fulfilled').value.accessToken;
        await t.test('catálogo SQL: CRUD autenticado, filtros, dinheiro e arquivamento preservando FK', async () => {
            const api = (method, path) => request(app)[method](path).set('Authorization', `Bearer ${adminToken}`);
            const created = await api('post', '/api/films').send({ titulo: 'SQL 100%_literal', duracao: 100, disponivel_streaming: true, preco_aluguel: '99999999.99' }).expect(201);
            const filmId = created.body.data.id_filme;
            assert.equal(created.body.data.preco_aluguel, '99999999.99');
            assert.equal(typeof filmId, 'string');
            const genre = await api('post', '/api/genres').send({ nome: 'SQL Fixture' }).expect(201);
            const genreId = genre.body.data.id_genero;
            await api('post', '/api/genres').send({ nome: 'SQL Fixture' }).expect(409);
            for (let i = 0; i < 2; i++) await api('post', `/api/films/${filmId}/genres`).send({ genreId }).expect(200);
            // Valor privado legado permite verificar projeções sem configurar CDN externo.
            await database.execute('UPDATE filmes SET url_reproducao = ? WHERE id_filme = ?', ['https://media.example.invalid/private', filmId]);
            const page = await request(app).get('/api/films').query({ genreId, titulo: '%_', streaming: 'true', limit: '1' }).expect(200);
            assert.equal(page.body.data.items.length, 1);
            assert.ok(!page.text.includes('url_reproducao')); assert.ok(!page.text.includes('/private'));
            const none = await request(app).get('/api/films').query({ cinema: 'false' }).expect(200);
            assert.equal(none.body.data.items.length, 0);
            await api('patch', `/api/films/${filmId}`).send({ titulo: 'SQL Updated' }).expect(200);
            await api('delete', `/api/genres/${genreId}`).expect(204);
            const linked = await request(app).get(`/api/films/${filmId}/genres`).expect(200);
            assert.equal(linked.body.data.items.length, 0);
            await api('delete', `/api/films/${filmId}`).expect(204);
            await request(app).get(`/api/films/${filmId}`).expect(404);
            await api('get', `/api/admin/films/${filmId}`).expect(200);
            const [[row]] = await database.execute('SELECT COUNT(*) AS total FROM filme_generos WHERE id_filme = ? AND id_genero = ?', [filmId, genreId]);
            assert.equal(Number(row.total), 1);
            const [[audit]] = await database.execute("SELECT COUNT(*) AS total FROM auditoria_eventos WHERE event_type = 'CATALOG.FILM_ARCHIVED'");
            assert.equal(Number(audit.total), 1);
        });
        await t.test('galeria SQL: principal única por tipo, imagem legada, arquivo e privacidade', async () => {
            const api = (method, path) => request(app)[method](path).set('Authorization', `Bearer ${adminToken}`);
            const filmId = (await api('post', '/api/films').send({ titulo: 'Galeria SQL', duracao: 90 }).expect(201)).body.data.id_filme;
            const source = await createImageStorage(config.imageUpload).put({ buffer: Buffer.from('fixture-webp') });
            const base = `/api/admin/films/${filmId}/images`;
            const body = { stagingKey: source.key, tipo: 'CAPA', principal: true, ordem: 0 };
            const first = (await api('post', base).send(body).expect(201)).body.data;
            const second = (await api('post', base).send({ ...body, ordem: 1 }).expect(201)).body.data;
            const [[principal]] = await database.execute("SELECT COUNT(*) AS total FROM filmes_imagens WHERE id_filme = ? AND tipo = 'CAPA' AND principal = TRUE", [filmId]);
            assert.equal(Number(principal.total), 1);
            await assert.rejects(database.execute('UPDATE filmes_imagens SET principal = TRUE WHERE id_imagem = ?', [first.id_imagem]), { code: 'ER_DUP_ENTRY' });
            const [[film]] = await database.execute('SELECT imagem FROM filmes WHERE id_filme = ?', [filmId]);
            assert.equal(film.imagem, second.url);
            await request(app).get(second.url).expect(200).expect('Content-Type', 'image/webp');
            await api('delete', `/api/films/${filmId}`).expect(204);
            await request(app).get(second.url).expect(404);
            await request(app).get(`/api/films/${filmId}/images`).expect(404);
            await api('get', base).expect(200);
        });
        await t.test('locais SQL: FK, duplicidade, capacidade e sala alheia', async () => {
            const api = (method, path) => request(app)[method](path).set('Authorization', `Bearer ${adminToken}`);
            const input = { nome: 'Local SQL', cidade: 'São Paulo', estado: 'SP' };
            const l1 = (await api('post', '/api/admin/locations').send(input).expect(201)).body.data.id_local;
            const l2 = (await api('post', '/api/admin/locations').send({ ...input, nome: 'Local SQL 2' }).expect(201)).body.data.id_local;
            const room = (await api('post', `/api/admin/locations/${l1}/rooms`).send({ nome: 'Sala SQL', capacidade: 1 }).expect(201)).body.data.id_sala;
            const base = `/api/admin/locations/${l1}/rooms/${room}`;
            await api('post', `/api/admin/locations/${l1}/rooms`).send({ nome: 'Sala SQL', capacidade: 1 }).expect(409);
            await assert.rejects(database.execute('INSERT INTO salas (id_local,nome,capacidade) VALUES (?,?,?)', ['4294967295', 'Sem local', 1]), { code: 'ER_NO_REFERENCED_ROW_2' });
            const seat = (await api('post', `${base}/seats`).send({ fileira: 'A', numero: 1, tipo: 'PCD' }).expect(201)).body.data.id_assento;
            await api('post', `${base}/seats`).send({ fileira: 'A', numero: 1 }).expect(409);
            await api('post', `${base}/seats`).send({ fileira: 'A', numero: 2 }).expect(409);
            await api('patch', base).send({ status: 'ATIVA' }).expect(200);
            await api('get', `/api/admin/locations/${l2}/rooms/${room}/seats/${seat}`).expect(404);
            const page = await request(app).get(`/api/locations/${l1}/rooms/${room}/seats?accessible=true`).expect(200);
            assert.equal(page.body.data.items.length, 1);
            assert.equal(page.body.data.items[0].id_assento, seat);
            await assert.rejects(database.execute('INSERT INTO assentos (id_sala,fileira,numero) VALUES (?,?,?)', ['4294967295', 'Z', 1]), { code: 'ER_NO_REFERENCED_ROW_2' });
        });
        await t.test('sessões SQL: corrida no local, meia-noite e direitos vendidos', async () => {
            const api = (method, path) => request(app)[method](path).set('Authorization', `Bearer ${adminToken}`);
            const location = (await api('post', '/api/admin/locations').send({ nome: 'Agenda SQL', cidade: 'São Paulo', estado: 'SP' }).expect(201)).body.data.id_local;
            const rooms = [];
            for (const name of ['A', 'B']) {
                const room = (await api('post', `/api/admin/locations/${location}/rooms`).send({ nome: name, capacidade: 1 }).expect(201)).body.data.id_sala;
                const seat = (await api('post', `/api/admin/locations/${location}/rooms/${room}/seats`).send({ fileira: 'A', numero: 1 }).expect(201)).body.data.id_assento;
                await api('patch', `/api/admin/locations/${location}/rooms/${room}`).send({ status: 'ATIVA' }).expect(200);
                rooms.push({ room, seat });
            }
            const film = (await api('post', '/api/films').send({ titulo: 'Agenda SQL', duracao: 60, disponivel_cinema: true }).expect(201)).body.data.id_filme;
            const input = (room, date, start, end) => ({ id_filme: film, id_sala: room, data: date, horario_inicio: start, horario_fim: end, preco_inteira: '20.00' });
            const race = await Promise.all([api('post', '/api/admin/sessions').send(input(rooms[0].room, '2026-10-10', '23:30', '00:30')),
                api('post', '/api/admin/sessions').send(input(rooms[1].room, '2026-10-11', '00:30', '02:00'))]);
            assert.deepEqual(race.map(r => r.status).sort(), [201, 409]);
            const winner = race.find(r => r.status === 201).body.data;
            assert.equal(winner.id_local, location);
            const [[count]] = await database.execute('SELECT COUNT(*) AS total FROM sessoes s JOIN salas sa ON sa.id_sala = s.id_sala WHERE sa.id_local = ?', [location]);
            assert.equal(Number(count.total), 1);
            // Pedido pago fixa os direitos da sessão, mesmo sem fluxo de checkout neste módulo.
            const [order] = await database.execute("INSERT INTO pedidos (id_usuario,status,valor_total) VALUES (?,'PAGO',?)", [String(legacy.id_usuario), '20.00']);
            const seat = rooms.find(r => r.room === winner.id_sala).seat;
            await database.execute('INSERT INTO itens_pedido (id_pedido,id_sessao,id_assento,quantidade,valor_unitario,subtotal) VALUES (?,?,?,?,?,?)', [String(order.insertId), winner.id_sessao, seat, 1, '20.00', '20.00']);
            await api('patch', `/api/admin/sessions/${winner.id_sessao}`).send({ horario_inicio: '21:00' }).expect(409);
            await api('delete', `/api/admin/sessions/${winner.id_sessao}`).expect(409);
        });
        await t.test('equipes SQL: sessão, convite pendente, UNIQUE e FK', async () => {
            const api = (method, path) => request(app)[method](path).set('Authorization', `Bearer ${adminToken}`);
            const [[session]] = await database.execute("SELECT id_sessao FROM sessoes WHERE status = 'AGENDADA' ORDER BY id_sessao DESC LIMIT 1");
            assert.ok(session);
            const hash = await hashPassword(password, 10);
            const [supervisor] = await database.execute("INSERT INTO usuarios (nome,email,cpf,senha,tipo_usuario,status) VALUES (?,?,?,?,'SUPERVISOR','ATIVO')", ['Supervisor Fixture', 'supervisor-team@example.invalid', '39053344705', hash]);
            const [collaborator] = await database.execute("INSERT INTO usuarios (nome,email,cpf,senha,tipo_usuario,status) VALUES (?,?,?,?,'COLABORADOR','ATIVO')", ['Colaborador Fixture', 'collaborator-team@example.invalid', '12345678909', hash]);
            const team = (await api('post', '/api/teams').send({ sessionId: String(session.id_sessao), nome: 'Equipe SQL', supervisorId: String(supervisor.insertId) }).expect(201)).body.data;
            const invite = (await api('post', `/api/teams/${team.id_equipe}/entries/invitations`).send({ userId: String(collaborator.insertId), funcao: 'Projeção' }).expect(201)).body.data;
            const [[notice]] = await database.execute('SELECT id_notificacao,lida FROM notificacoes WHERE id_usuario = ? AND dedupe_key = ?', [String(collaborator.insertId), `team-invitation:${invite.id_entrada}`]);
            assert.ok(notice);
            assert.equal(Number(notice.lida), 0);
            await assert.rejects(database.execute('INSERT INTO notificacoes (id_usuario,titulo,dedupe_key) VALUES (?,?,?)', [String(collaborator.insertId), 'Duplicada', `team-invitation:${invite.id_entrada}`]), { code: 'ER_DUP_ENTRY' });
            const [[before]] = await database.execute('SELECT COUNT(*) AS total FROM equipe_membros WHERE id_equipe = ?', [team.id_equipe]);
            assert.equal(Number(before.total), 0);
            await api('post', `/api/teams/${team.id_equipe}/entries/invitations`).send({ userId: String(collaborator.insertId), funcao: 'Portaria' }).expect(409);
            await assert.rejects(database.execute("INSERT INTO equipe_entradas (id_equipe,id_usuario,id_emissor,tipo,status) VALUES (?,?,?,'CONVITE','PENDENTE')", [team.id_equipe, String(collaborator.insertId), String(supervisor.insertId)]), { code: 'ER_DUP_ENTRY' });
            await assert.rejects(database.execute("INSERT INTO equipe_entradas (id_equipe,id_usuario,id_emissor,tipo,status) VALUES (?,?,?,'CONVITE','PENDENTE')", ['4294967295', String(collaborator.insertId), String(supervisor.insertId)]), { code: 'ER_NO_REFERENCED_ROW_2' });
        });
        await t.test('chamados SQL: convite aceito, duplo aceite e histórico transacional', async () => {
            const adminApi = (method, path) => request(app)[method](path).set('Authorization', `Bearer ${adminToken}`);
            const [[team]] = await database.execute("SELECT id_equipe,id_sessao FROM equipes WHERE nome = 'Equipe SQL' ORDER BY id_equipe DESC LIMIT 1");
            const [[firstUser]] = await database.execute('SELECT id_usuario FROM usuarios WHERE email = ?', ['collaborator-team@example.invalid']);
            const firstAuth = await identity.login({ email: 'collaborator-team@example.invalid', password });
            const firstApi = (method, path) => request(app)[method](path).set('Authorization', `Bearer ${firstAuth.accessToken}`);
            const [[entry]] = await database.execute("SELECT id_entrada FROM equipe_entradas WHERE id_equipe = ? AND id_usuario = ? AND status = 'PENDENTE'", [String(team.id_equipe), String(firstUser.id_usuario)]);
            await firstApi('post', `/api/teams/${team.id_equipe}/entries/${entry.id_entrada}/decision`).send({ decision: 'ACEITAR' }).expect(200);
            const hash = await hashPassword(password, 10);
            const [secondUser] = await database.execute("INSERT INTO usuarios (nome,email,cpf,senha,tipo_usuario,status) VALUES (?,?,?,?,'COLABORADOR','ATIVO')", ['Colaborador 2', 'collaborator-team-2@example.invalid', '98765432100', hash]);
            const secondEntry = (await adminApi('post', `/api/teams/${team.id_equipe}/entries/invitations`).send({ userId: String(secondUser.insertId), funcao: 'Apoio' }).expect(201)).body.data;
            const secondAuth = await identity.login({ email: 'collaborator-team-2@example.invalid', password });
            const secondApi = (method, path) => request(app)[method](path).set('Authorization', `Bearer ${secondAuth.accessToken}`);
            await secondApi('post', `/api/teams/${team.id_equipe}/entries/${secondEntry.id_entrada}/decision`).send({ decision: 'ACEITAR' }).expect(200);
            const base = `/api/teams/${team.id_equipe}/chamados`;
            const created = (await adminApi('post', base).send({ titulo: 'Projeção SQL', prioridade: 'ALTA' }).expect(201)).body.data;
            assert.equal(created.id_sessao, String(team.id_sessao));
            const results = await Promise.all([firstApi('post', `${base}/${created.id_chamado}/accept`), secondApi('post', `${base}/${created.id_chamado}/accept`)]);
            assert.deepEqual(results.map(r => r.status).sort(), [200, 409]);
            const [[row]] = await database.execute('SELECT id_responsavel,status FROM chamados WHERE id_chamado = ?', [created.id_chamado]);
            assert.equal(row.status, 'EM_ANDAMENTO');
            const [[events]] = await database.execute("SELECT COUNT(*) AS total FROM chamado_eventos WHERE id_chamado = ? AND acao = 'ACEITO'", [created.id_chamado]);
            assert.equal(Number(events.total), 1);
            const winnerApi = String(row.id_responsavel) === String(firstUser.id_usuario) ? firstApi : secondApi;
            await winnerApi('post', `${base}/${created.id_chamado}/resolve`).expect(200);
            await winnerApi('post', `${base}/${created.id_chamado}/close`).expect(200);
            await adminApi('get', `/api/teams/4294967295/chamados/${created.id_chamado}`).expect(404);
        });
        await t.test('fornecedores SQL: nome_cine final, CNPJ normalizado e acesso próprio', async () => {
            const api = (method, path) => request(app)[method](path).set('Authorization', `Bearer ${adminToken}`);
            const [[column]] = await database.execute("SELECT COUNT(*) AS total FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'fornecedores' AND COLUMN_NAME = 'nome_cine'");
            assert.equal(Number(column.total), 1);
            const hash = await hashPassword(password, 10);
            const [user] = await database.execute("INSERT INTO usuarios (nome,email,cpf,senha,tipo_usuario,status) VALUES (?,?,?,?,'FORNECEDOR','ATIVO')", ['Fornecedor Fixture', 'supplier-sql@example.invalid', '22233344405', hash]);
            const created = (await api('post', '/api/admin/suppliers').send({ userId: String(user.insertId), razao_social: 'Fornecedor SQL', nome_cine: 'Cinema SQL', cnpj: '00.000.000/E08G-12' }).expect(201)).body.data;
            assert.equal(created.cnpj, '00000000E08G12');
            assert.equal(created.nome_cine, 'Cinema SQL');
            const authSupplier = await identity.login({ email: 'supplier-sql@example.invalid', password });
            const supplierApi = (method, path) => request(app)[method](path).set('Authorization', `Bearer ${authSupplier.accessToken}`);
            const mine = await supplierApi('get', '/api/suppliers/me').expect(200);
            assert.equal(mine.body.data.id_fornecedor, created.id_fornecedor);
            assert.ok(!('cnpj' in mine.body.data));
            await supplierApi('get', `/api/admin/suppliers/${created.id_fornecedor}`).expect(403);
            const [other] = await database.execute("INSERT INTO usuarios (nome,email,cpf,senha,tipo_usuario,status) VALUES (?,?,?,?,'FORNECEDOR','ATIVO')", ['Outro Fornecedor', 'supplier-sql-2@example.invalid', '33344455506', hash]);
            await assert.rejects(database.execute("INSERT INTO fornecedores (id_usuario,razao_social,cnpj) VALUES (?,?,?)", [String(other.insertId), 'Duplicado', '00.000.000/e08g-12']), { code: 'ER_DUP_ENTRY' });
            await api('delete', `/api/admin/suppliers/${created.id_fornecedor}`).expect(204);
            const [[archived]] = await database.execute('SELECT status FROM fornecedores WHERE id_fornecedor = ?', [created.id_fornecedor]);
            assert.equal(archived.status, 'INATIVO');
        });
        await t.test('insumos/equipamentos SQL: vínculo, patrimônio e saldo protegido', async () => {
            const adminApi = (method, path) => request(app)[method](path).set('Authorization', `Bearer ${adminToken}`);
            const [[supplier]] = await database.execute('SELECT id_fornecedor FROM fornecedores WHERE cnpj = ?', ['00000000E08G12']);
            const [[otherUser]] = await database.execute('SELECT id_usuario FROM usuarios WHERE email = ?', ['supplier-sql-2@example.invalid']);
            const [otherSupplier] = await database.execute("INSERT INTO fornecedores (id_usuario,razao_social,cnpj) VALUES (?,?,?)", [String(otherUser.id_usuario), 'Outro fornecedor', '11111111111111']);
            await adminApi('patch', `/api/admin/suppliers/${supplier.id_fornecedor}`).send({ status: 'ATIVO' }).expect(200);
            const local = (await adminApi('post', '/api/admin/locations').send({ nome: 'Estoque SQL', cidade: 'São Paulo', estado: 'SP' }).expect(201)).body.data.id_local;
            await adminApi('post', `/api/admin/suppliers/${supplier.id_fornecedor}/locations`).send({ localId: local }).expect(201);
            const ownAuth = await identity.login({ email: 'supplier-sql@example.invalid', password });
            const otherAuth = await identity.login({ email: 'supplier-sql-2@example.invalid', password });
            const own = (method, path) => request(app)[method](path).set('Authorization', `Bearer ${ownAuth.accessToken}`);
            const other = (method, path) => request(app)[method](path).set('Authorization', `Bearer ${otherAuth.accessToken}`);
            await other('post', '/api/inputs').send({ localId: local, nome: 'Invasão', preco: '1.00' }).expect(403);
            const input = (await own('post', '/api/inputs').send({ localId: local, nome: 'Milho SQL', preco: '12.30', quantidade_minima: 2 }).expect(201)).body.data;
            assert.equal(input.quantidade, 0);
            assert.equal(input.preco, '12.30');
            await own('patch', `/api/inputs/${input.id_insumo}`).send({ quantidade: 500 }).expect(422);
            await own('patch', `/api/inputs/${input.id_insumo}`).send({ custo: '1.00' }).expect(422);
            await other('get', `/api/inputs/${input.id_insumo}`).expect(403);
            const equipment = (await own('post', '/api/equipment').send({ localId: local, nome: 'Projetor SQL', numero_patrimonio: 'Pat-SQL-1' }).expect(201)).body.data;
            assert.equal(equipment.quantidade, 0);
            await own('post', '/api/equipment').send({ localId: local, nome: 'Outro projetor', numero_patrimonio: ' pat-sql-1 ' }).expect(409);
            await own('delete', `/api/equipment/${equipment.id_equipamento}`).expect(204);
            const [[archived]] = await database.execute('SELECT status,quantidade FROM equipamentos WHERE id_equipamento = ?', [equipment.id_equipamento]);
            assert.equal(archived.status, 'INDISPONIVEL');
            assert.equal(archived.quantidade, 0);
            const [[grant]] = await database.execute('SELECT status FROM fornecedor_locais WHERE id_fornecedor = ? AND id_local = ?', [String(supplier.id_fornecedor), local]);
            assert.equal(grant.status, 'ATIVO');
            assert.notEqual(String(otherSupplier.insertId), String(supplier.id_fornecedor));
        });
        await t.test('combos SQL: composição no local, FK e referência histórica', async () => {
            const adminApi = (method, path) => request(app)[method](path).set('Authorization', `Bearer ${adminToken}`);
            const [[input]] = await database.execute("SELECT id_insumo,id_local FROM insumos WHERE nome = 'Milho SQL' ORDER BY id_insumo DESC LIMIT 1");
            const [[supplier]] = await database.execute('SELECT id_fornecedor FROM fornecedores WHERE cnpj = ?', ['00000000E08G12']);
            const otherLocal = (await adminApi('post', '/api/admin/locations').send({ nome: 'Outro Estoque SQL', cidade: 'São Paulo', estado: 'SP' }).expect(201)).body.data.id_local;
            await adminApi('post', `/api/admin/suppliers/${supplier.id_fornecedor}/locations`).send({ localId: otherLocal }).expect(201);
            const otherInput = (await adminApi('post', '/api/inputs').send({ supplierId: String(supplier.id_fornecedor), localId: otherLocal, nome: 'Copo SQL', preco: '1.00' }).expect(201)).body.data.id_insumo;
            const base = { localId: String(input.id_local), nome: 'Combo SQL', preco: '20.00' };
            await adminApi('post', '/api/admin/combos').send({ ...base, items: [{ inputId: otherInput, quantidade: 1 }] }).expect(409);
            const combo = (await adminApi('post', '/api/admin/combos').send({ ...base, items: [{ inputId: String(input.id_insumo), quantidade: 2 }] }).expect(201)).body.data;
            assert.equal(combo.items[0].quantidade, 2);
            const visible = await request(app).get(`/api/combos?localId=${input.id_local}`).expect(200);
            assert.ok(visible.body.data.items.some(row => row.id_combo === combo.id_combo));
            await assert.rejects(database.execute('INSERT INTO combo_itens (id_combo,id_insumo,quantidade) VALUES (?,?,?)', [combo.id_combo, String(input.id_insumo), 1]), { code: 'ER_DUP_ENTRY' });
            const [[customer]] = await database.execute("SELECT id_usuario FROM usuarios WHERE tipo_usuario = 'CLIENTE' ORDER BY id_usuario LIMIT 1");
            const [order] = await database.execute('INSERT INTO pedidos (id_usuario) VALUES (?)', [String(customer.id_usuario)]);
            await database.execute('INSERT INTO itens_pedido (id_pedido,id_combo,quantidade,valor_unitario,subtotal) VALUES (?,?,1,?,?)', [String(order.insertId), combo.id_combo, '20.00', '20.00']);
            await adminApi('put', `/api/admin/combos/${combo.id_combo}/items`).send({ items: [{ inputId: String(input.id_insumo), quantidade: 3 }] }).expect(409);
            await adminApi('patch', `/api/admin/combos/${combo.id_combo}`).send({ preco: '21.00' }).expect(409);
            await adminApi('delete', `/api/admin/combos/${combo.id_combo}`).expect(204);
            const [[archived]] = await database.execute('SELECT ativo FROM combos WHERE id_combo = ?', [combo.id_combo]);
            assert.equal(Number(archived.ativo), 0);
        });
    });
    // Preserva evidência no schema _test. Limpeza/recriação pelo operador, nunca DROP DATABASE automático.
});
